export const SET_ANDROID_DEVICES = "SET_ANDROID_DEVICES"
export const SET_APPLE_DEVICES = "SET_APPLE_DEVICES"
export const SET_SINGLE_DEVICE = "SET_SINGLE_DEVICE" 
export const RESET_SINGLE_DEVICE = "RESET_SINGLE_DEVICE"